Update

diff --git a/BE-sprint-master-ai/Dockerfile b/BE-sprint-master-ai/Dockerfile
--- a/BE-sprint-master-ai/Dockerfile
+++ b/BE-sprint-master-ai/Dockerfile
@@ -1,33 +1,27 @@
 # To use this Dockerfile, you have to set `output: 'standalone'` in your next.config.mjs file.
 # From https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
 
-FROM node:20.19.0-alpine AS base
+FROM node:22.17.0-alpine AS base
 
 # Install dependencies only when needed
 FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
-RUN apk add --no-cache libc6-compat python3 make g++
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
 # Install dependencies based on the preferred package manager
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 RUN \
   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm install; \
+  elif [ -f package-lock.json ]; then npm ci; \
   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
-  else echo "Lockfile not found. Falling back to npm install" && npm install; \
+  else echo "Lockfile not found." && exit 1; \
   fi
 
 
 # Rebuild the source code only when needed
 FROM base AS builder
 WORKDIR /app
-ARG PAYLOAD_SECRET
-ARG ENABLE_FIRST_ADMIN_BOOTSTRAP
-ARG FIRST_ADMIN_BOOTSTRAP_TOKEN
-ENV PAYLOAD_SECRET=$PAYLOAD_SECRET
-ENV ENABLE_FIRST_ADMIN_BOOTSTRAP=$ENABLE_FIRST_ADMIN_BOOTSTRAP
-ENV FIRST_ADMIN_BOOTSTRAP_TOKEN=$FIRST_ADMIN_BOOTSTRAP_TOKEN
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
@@ -40,7 +34,7 @@ RUN \
   if [ -f yarn.lock ]; then yarn run build; \
   elif [ -f package-lock.json ]; then npm run build; \
   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-  else echo "Lockfile not found. Using npm build" && npm run build; \
+  else echo "Lockfile not found." && exit 1; \
   fi
 
 # Production image, copy all the files and run next
@@ -48,29 +42,30 @@ FROM base AS runner
 WORKDIR /app
 
 ENV NODE_ENV production
-ARG PAYLOAD_SECRET
-ARG ENABLE_FIRST_ADMIN_BOOTSTRAP
-ARG FIRST_ADMIN_BOOTSTRAP_TOKEN
-ENV PAYLOAD_SECRET=$PAYLOAD_SECRET
-ENV ENABLE_FIRST_ADMIN_BOOTSTRAP=$ENABLE_FIRST_ADMIN_BOOTSTRAP
-ENV FIRST_ADMIN_BOOTSTRAP_TOKEN=$FIRST_ADMIN_BOOTSTRAP_TOKEN
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
 
-COPY --from=builder /app/package.json ./package.json
+# Remove this line if you do not have this folder
+COPY --from=builder /app/public ./public
 
-COPY --from=builder /app/public* ./public/ 
-
+# Set the correct permission for prerender cache
 RUN mkdir .next
 RUN chown nextjs:nodejs .next
 
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
 USER nextjs
 
 EXPOSE 3000
+
 ENV PORT 3000
 
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
 CMD HOSTNAME="0.0.0.0" node server.js
